import utils.Utils

import java.nio.file.Path

//noinspection TypeAnnotation
object TaskContext {
  extension (path: Path) {
    def /(subpath: String) = path.resolve(subpath)
  }

  lazy val exam = Utils.getSystemPropertyObject[assessments.Exam]("current.exam", "the current exam")
  lazy val lecturePrivateDir = Utils.sharedFile("2026-ss-intro-qc")
  /** Directory with all the grading result files (PDF/HTML) to give to students.
   * Subdirs are the registration numbers. Generated by [[TaskGradeEveryone]] */
  lazy val gradingReportDir = lecturePrivateDir / "exam1/reports"
  /** Spreadsheet with all students that took the exam. It's ok if there are additional students in there.
   * Not autogenerated. */
  lazy val allStudents = lecturePrivateDir / "exam1/all-participating-students-with-name-regno-email.csv"
  /** Spreadsheet with the results of the grading. Columns student;points;grade.
   * Generated by [[TaskGradeEveryone]] */
  lazy val gradingResultSpreadsheet = gradingReportDir / "results.csv"
  lazy val scieboRoot = Path.of("/home/unruh/cloud/sciebo")
  /** Copy of [[gradingReportDir]] files, in a shared folder. Students get live access to it.
   * Must be manually copied over from [[gradingReportDir]]. */
  lazy val scieboReportDir = scieboRoot / "shared/iqc-2026-exam1-grading/reports"
}