import utils.Utils

import java.nio.file.Path

//noinspection TypeAnnotation
object TaskContext {
  extension (path: Path) {
    def /(subpath: String) = path.resolve(subpath)
  }

  lazy val exam = Utils.getSystemPropertyObject[assessments.Exam]("current.exam", "the current exam")
  lazy val lecturePrivateDir = Utils.sharedFile("2026-ss-intro-qc")
  lazy val examPrivateDir = lecturePrivateDir / "exam1"
  /** Directory with all the grading result files (PDF/HTML) to give to students.
   * Subdirs are the registration numbers. Generated by [[TaskGradeEveryone]] */
  lazy val gradingReportDir = lecturePrivateDir / "exam1/reports"
  /** Spreadsheet with all students that took the exam. It's ok if there are additional students in there.
   * Headers: name;registration;email.
   * Not autogenerated. */
  lazy val allStudents = lecturePrivateDir / "exam1/all-participating-students-with-name-regno-email.csv"
  /** Grade sheet for RWTHonline. Used for reading/writing. Download and upload to RWTHonline manually */
  lazy val rwthOnlineCSV = lecturePrivateDir / "exam1/rwth-online-grades.csv"
  /** Spreadsheet with the results of the grading. Columns student;points;grade.
   * Generated by [[TaskGradeEveryone]] */
  lazy val gradingResultSpreadsheet = gradingReportDir / "results.csv"
  /** HTML file with the grade distribution (table + histogram). Generated by [[TaskGradeDistribution]]. */
  lazy val gradeDistributionHtml = gradingReportDir / "grade-distribution.html"
  lazy val scieboRoot = Path.of("/home/unruh/cloud/sciebo")
  /** Copy of [[gradingReportDir]] files, in a shared folder. Students get live access to it.
   * Must be manually copied over from [[gradingReportDir]]. */
  lazy val scieboReportDir = scieboRoot / "shared/iqc-2026-exam1-grading/reports"
  /** Copy of [[gradingResultSpreadsheet]], in Sciebo. */
  lazy val scieboGradingResultSpreadsheet = scieboReportDir / "results.csv"
  /** Directory where to create the lecture certificates (Schein). Created if needed. */
  lazy val scheinDir = examPrivateDir / "schein"
}